export enum UserPermission {
    BOOK_VIEW = 'BOOK_VIEW',
    BOOK_CREATE = 'BOOK_CREATE',
    BOOK_UPDATE = 'BOOK_UPDATE',
    BOOK_DELETE = 'BOOK_DELETE',

    USER_VIEW = 'USER_VIEW',
    USER_UPDATE_ROLE = 'USER_UPDATE_ROLE',
    USER_UPDATE_STATUS = 'USER_UPDATE_STATUS',

    LOAN_VIEW = 'LOAN_VIEW',
    LOAN_CREATE = 'LOAN_CREATE',
    LOAN_CONFIRM = 'LOAN_CONFIRM',
    LOAN_BORROWING = 'LOAN_BORROWING',
    LOAN_DETAIL_RETURN = 'LOAN_DETAIL_RETURN',
    LOAN_CANCEL = 'LOAN_CANCEL',

    CATEGORY_VIEW = 'CATEGORY_VIEW',
    CATEGORY_CREATE = 'CATEGORY_CREATE',
    CATEGORY_UPDATE = 'CATEGORY_UPDATE',
    CATEGORY_DELETE = 'CATEGORY_DELETE',

    SUB_CATEGORY_VIEW = 'SUB_CATEGORY_VIEW',
    SUB_CATEGORY_CREATE = 'SUB_CATEGORY_CREATE',
    SUB_CATEGORY_UPDATE = 'SUB_CATEGORY_UPDATE',
    SUB_CATEGORY_DELETE = 'SUB_CATEGORY_DELETE',

    PERMISSION_MANAGE = 'PERMISSION_MANAGE',
}