export enum UserPermission {
    BOOK_VIEW = 'BOOK_VIEW',
    BOOK_CREATE = 'BOOK_CREATE',
    BOOK_UPDATE = 'BOOK_UPDATE',
    BOOK_DELETE = 'BOOK_DELETE',

    USER_VIEW = 'USER_VIEW',
    USER_UPDATE_ROLE = 'USER_UPDATE_ROLE',

    PERMISSION_MANAGE = 'PERMISSION_MANAGE',
}